### ISSUE TITLE
Problem with pinch zoom

### ISSUE THREAD

**Issue by kirich1409** [Baseflow/PhotoView#104]
Problem when I try to pinch image in ViewPager.

![screenshot_2013-10-30-16-56-19](https://f.cloud.github.com/assets/2403657/1437309/24c9955e-416b-11e3-9782-be5ec16db895.png)

**Comment by SrishtiRoy** [comment]
Is it possible to use Photoview in a single activity without Viewpager ,  I am getting array index out of bound exception while zooming for the same

**Comment by SrishtiRoy** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                     at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
                                                     at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
                                                     at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1434)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:2775)

**Comment by Jawnnypoo** [comment]
Take a look at the Readme or the sample
