### ISSUE TITLE
Problem with PagerAdapter(?)

### ISSUE THREAD

**Issue by MasterGroosha** [Baseflow/PhotoView#154]
Hello and sorry for my bad English.
I'm having a strange issue.
On the opening of my activity, some images are downloaded from internet as bitmaps and placed to your HackyViewPager.
However, sometimes the app crashes with very strange error:

```
ru.mastergroosha.yaruclient fatal error : The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 1 Pager id: ru.mastergroosha.yaruclient:id/photo_viewer_pager Pager class: class ru.mastergroosha.yaruclient.secondary.classes.HackyViewPager Problematic adapter: class ru.mastergroosha.yaruclient.Photo_Viewer$SamplePagerAdapter
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 1 Pager id: ru.mastergroosha.yaruclient:id/photo_viewer_pager Pager class: class ru.mastergroosha.yaruclient.secondary.classes.HackyViewPager Problematic adapter: class ru.mastergroosha.yaruclient.Photo_Viewer$SamplePagerAdapter
    at android.support.v4.view.ViewPager.populate(ViewPager.java:962)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1436)
    at android.view.View.measure(View.java:16497)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
    at android.view.View.measure(View.java:16497)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:16497)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:327)
    at android.view.View.measure(View.java:16497)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
    at android.view.View.measure(View.java:16497)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
    at android.view.Choreographer.doFrame(Choreographer.java:544)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5017)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
    at dalvik.system.NativeStart.main(Native Method)
```

I like this string: "changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!"
but on onPostExecute() of my AsyncTask I have

```
sp.notifyDataSetChanged();
```

where 

```
SamplePagerAdapter sp = new SamplePagerAdapter();
```

 and it's edited correctly

**Comment by PyBird** [comment]
How?
