### ISSUE TITLE
PhotoView Crashes in Activity with NavigationDrawer

### ISSUE THREAD

**Issue by zaur** [Baseflow/PhotoView#189]
I have an Activity with NavigationDrawer and fragment with PhotoView.
App crashes after some scaling of photo.

Stacktrace:

```
   java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1004)
            at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:921)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2055)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2295)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1622)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2565)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2243)
            at android.view.View.dispatchPointerEvent(View.java:8343)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4702)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4570)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4182)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4151)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4262)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4159)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4319)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4182)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4151)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4159)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6499)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6416)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6387)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6352)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6579)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6552)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6598)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
            at android.view.Choreographer.doCallbacks(Choreographer.java:603)
            at android.view.Choreographer.doFrame(Choreographer.java:571)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5476)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dainhan90** [comment]
I use this solution, but not fixed
