### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by jiaoyongzhi** [Baseflow/PhotoView#799]
### Configuration

**Version:** 1.x

**Platform:** :robot: Android 9.x  java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2371)
	at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3124)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3124)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3124)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3124)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3124)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3124)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:570)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1963)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4071)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:523)
	at android.view.View.dispatchPointerEvent(View.java:13823)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5694)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5155)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5218)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5179)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5336)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5187)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5393)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5155)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5218)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5179)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5187)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5155)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7968)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7937)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7894)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8112)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:206)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:340)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by jiaoyongzhi** [comment]
vivo V2031A  android 10

**Comment by prashasth-nair** [comment]
Insted of 
`implementation 'com.github.chrisbanes:PhotoView:2.0.0'`

Use 
`implementation 'com.github.chrisbanes:PhotoView:master-SNAPSHOT'`

**Comment by dbeqiraj** [comment]
Using version `2.3.0` and the bug is still present.

**Comment by PhantomLord72** [comment]
where is 2.3.0 ?!?!?!
