### ISSUE TITLE
Crash On zoomout Image 

### ISSUE THREAD

**Issue by jayesh0881** [Baseflow/PhotoView#805]
when zoom in or out smoothly it was working file but when zoom disastrously its crash app 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vnerds.kisnaapp, PID: 26386
    java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2754)
        at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3400)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:736)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4038)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:694)
        at android.view.View.dispatchPointerEvent(View.java:14643)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6539)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6326)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5764)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5817)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5783)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5939)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5791)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5996)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5764)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5817)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5783)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5791)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5764)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8976)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8837)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8790)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9112)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9052)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9139)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

**Comment by feelsoftware** [comment]
https://github.com/Baseflow/PhotoView#issues-with-viewgroups
